#注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8760/eureka
    #健康监测
    healthcheck:
      enabled: true

#微服务实例名字
spring:
  application:
    name: eureka-client1
server:
  port: 8762
  #feign日志
logging:
  level:
    com.baizhi.feign.TestFeign: debug
    #健康监测
management:
  security:
    enabled: false
    #feign的断路器
feign:
  hystrix:
    enabled: true
