eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8760/eureka
    healthcheck:
      enabled: true

spring:
  application:
    name: eureka-client1
 
server:
  port: 8762
logging:
  level:
    com.baizhi.feign.TestFeign: debug
management:
  security:
    enabled: false
feign:
  hystrix:
    enabled: true
